name: Fetch GH Sponsors
description: 'Updates the GitHub spondors list for the Monogame website'
author: 'MonoGame Foundation'
runs:
  using: "composite"
  steps:
    - name: Fetch
      if: runner.os == 'Linux'
      run: |
        QUERY='query($login:String!){
          organization(login:$login){
            monthlyEstimatedSponsorsIncomeInCents
            sponsorshipsAsMaintainer(first:1){ totalCount }
          }
        }'
        RESP=$(curl -s https://api.github.com/graphql \
          -H "Authorization: Bearer $GH_TOKEN" \
          -H "Content-Type: application/json" \
          -d "{\"query\":\"$QUERY\",\"variables\":{\"login\":\"$GH_LOGIN\"}}")

        echo "=== Raw GraphQL response ==="
        echo "$RESP"
        echo "============================"

        CENTS=$(echo "$RESP" | jq '.data.organization.monthlyEstimatedSponsorsIncomeInCents // 0')
        COUNT=$(echo "$RESP" | jq '.data.organization.sponsorshipsAsMaintainer.totalCount // 0')
        jq -n --argjson sum "$CENTS" --argjson count "$COUNT" \
          '{ sponsor_sum: ($sum/100|floor), sponsor_count: $count }' \
          > website/_data/gh_sponsors.json
      shell: bash