name: Fetch Patreons
description: 'Updates the Patreon list for the Monogame website'
author: 'MonoGame Foundation'
runs:
  using: "composite"
  steps:
    - name: Fetch
      if: runner.os == 'Linux'
      run: |
        ./fetch_patreon_memberships.sh
      shell: bash