name: Test Build Website

on:
  pull_request:
    branches:
      - 'main'

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write           

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  test:
    runs-on: ubuntu-latest
    concurrency: ci-${{ github.ref }}
    steps:
      - name: Clone Repository
        uses: actions/checkout@v4

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Build fxccs
        run: dotnet build fxccs/fxccs.csproj

      - name: Restore NPM Packages
        run: npm install

      - name: Build Site
        run: npm run build

  complete:
      runs-on: ubuntu-latest
      needs: test
      name: Test completion task
      steps:
        - run: echo "Tests Complete"